language: node_js
sudo: false

node_js:
  - '4'
  - '5'
  - '6.0'
  - '6'
  - '7'
  - '8.0'
  - '8'
  - '9'
  - '10.0'
  - '10'
  - '11.0'
  - '11'
  - 'node'

after_script:
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js

cache:
  directories:
    - node_modules
